In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"C:\Users\VAIBHAV\Desktop\Git Upload  data science\census-income (7).csv")

In [3]:
data.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country          
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [4]:
#data.rename({' ': 'Income'},inplace= True)
data.columns = data.columns.str.strip()

data.rename({'': 'Income'}, inplace=True)


In [5]:
data.rename({"": 'Income'}, inplace=True)


In [6]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', ''],
      dtype='object')

In [7]:
data.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country          
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [8]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
                  0
dtype: int64

In [9]:
data.columns = ['Income' if col == '' else col for col in data.columns]


In [10]:
print(data.columns)



Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'Income'],
      dtype='object')


In [11]:
data['Income'].value_counts()

Income
 <=50K    24720
 >50K      7841
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [15]:
 
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = labelencoder.fit_transform(data[col])


In [16]:
data

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1          2174             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0         15024             0   

       hours-per-week  native-country  Income  
0                  40              39       0  
1                  13              39       0  
2                  40              39       0  
3                  40              39       0  
4                  40               5       0  
...               ...             ...     ...  
32556              38              39       0  
32557              40              39       1  
32558              40              39       0  
32559              20              39       0  
32560              40              39       1  

[32561 rows x 15 columns]

In [17]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(X):
  """Calculates VIF for each feature in a DataFrame"""
  vif = pd.DataFrame()
  vif['feature'] = X.columns
  vif['vif'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
  return vif

# Assuming 'data' is your DataFrame
col_list = [col for col in data.columns if (data[col].dtype != 'object') & (col != 'price')]
x = data[col_list]

vif_data = calculate_vif(x)
print(vif_data)


           feature        vif
0              age   8.612915
1        workclass   8.492594
2           fnlwgt   4.033151
3        education   9.239470
4    education-num  19.641550
5   marital-status   4.071643
6       occupation   3.711141
7     relationship   2.649283
8             race  17.591432
9              sex   4.462940
10    capital-gain   1.083818
11    capital-loss   1.078968
12  hours-per-week  12.202241
13  native-country  19.823951
14          Income   1.740995


In [18]:
data = data.drop('native-country',axis=1)

In [19]:
data

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
...    ...        ...     ...        ...            ...             ...   
32556   27          4  257302          7             12               2   
32557   40          4  154374         11              9               2   
32558   58          4  151910         11              9               6   
32559   22          4  201490         11              9               4   
32560   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1          2174             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0         15024             0   

       hours-per-week  Income  
0                  40       0  
1                  13       0  
2                  40       0  
3                  40       0  
4                  40       0  
...               ...     ...  
32556              38       0  
32557              40       1  
32558              40       0  
32559              20       0  
32560              40       1  

[32561 rows x 14 columns]

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(X):
  """Calculates VIF for each feature in a DataFrame"""
  vif = pd.DataFrame()
  vif['feature'] = X.columns
  vif['vif'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
  return vif

# Assuming 'data' is your DataFrame
col_list = [col for col in data.columns if (data[col].dtype != 'object') & (col != 'price')]
x = data[col_list]

vif_data = calculate_vif(x)
print(vif_data)



           feature        vif
0              age   8.249929
1        workclass   8.448272
2           fnlwgt   4.019951
3        education   9.135969
4    education-num  19.047660
5   marital-status   4.000420
6       occupation   3.709438
7     relationship   2.569646
8             race  15.592699
9              sex   4.415341
10    capital-gain   1.083145
11    capital-loss   1.078859
12  hours-per-week  11.991048
13          Income   1.732457


In [23]:
data = data.drop('education-num',axis=1)

KeyError: "['education-num'] not found in axis"

In [24]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(X):
  """Calculates VIF for each feature in a DataFrame"""
  vif = pd.DataFrame()
  vif['feature'] = X.columns
  vif['vif'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
  return vif

# Assuming 'data' is your DataFrame
col_list = [col for col in data.columns if (data[col].dtype != 'object') & (col != 'Income')]
x = data[col_list]

vif_data = calculate_vif(x)
print(vif_data)



           feature        vif
0              age   7.927582
1        workclass   8.388845
2           fnlwgt   4.006871
3        education   7.367449
4   marital-status   3.846445
5       occupation   3.633933
6     relationship   2.511427
7             race  14.934160
8              sex   4.395634
9     capital-gain   1.034838
10    capital-loss   1.056950
11  hours-per-week  11.319827


In [25]:
data = data.drop('race',axis=1)

In [26]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(X):
  """Calculates VIF for each feature in a DataFrame"""
  vif = pd.DataFrame()
  vif['feature'] = X.columns
  vif['vif'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
  return vif

# Assuming 'data' is your DataFrame
col_list = [col for col in data.columns if (data[col].dtype != 'object') & (col != 'Income')]
x = data[col_list]

vif_data = calculate_vif(x)
print(vif_data)



           feature        vif
0              age   7.153594
1        workclass   8.129126
2           fnlwgt   3.943068
3        education   7.061767
4   marital-status   3.712597
5       occupation   3.623690
6     relationship   2.435129
7              sex   4.255762
8     capital-gain   1.034171
9     capital-loss   1.056931
10  hours-per-week  10.681525


In [27]:
data = data.drop('hours-per-week',axis=1)

In [28]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(X):
  """Calculates VIF for each feature in a DataFrame"""
  vif = pd.DataFrame()
  vif['feature'] = X.columns
  vif['vif'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
  return vif

# Assuming 'data' is your DataFrame
col_list = [col for col in data.columns if (data[col].dtype != 'object') & (col != 'Income')]
x = data[col_list]

vif_data = calculate_vif(x)
print(vif_data)



          feature       vif
0             age  6.519352
1       workclass  7.619477
2          fnlwgt  3.884730
3       education  6.614716
4  marital-status  3.703497
5      occupation  3.587296
6    relationship  2.415508
7             sex  3.945847
8    capital-gain  1.032615
9    capital-loss  1.055479


In [29]:
X = data.drop('Income',axis=1)
y = data['Income']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=557)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [32]:
X_train = sc.fit_transform(X_train)

In [33]:
X_test = sc.fit_transform(X_test)

In [34]:
y_test

16281    0
10657    1
2378     0
16541    0
30103    1
        ..
19474    1
18710    0
2135     0
27647    0
14139    0
Name: Income, Length: 6513, dtype: int32

# Logistic Regression

In [38]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegressionsion()

In [39]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [40]:
y_pred = logreg.predict(X_test)

In [42]:
from sklearn import metrics

In [43]:
logreg.score(X_test,y_test)

0.7982496545370796

In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4771,  187],
       [1127,  428]], dtype=int64)

In [55]:
a=4771+428
b=187+1127
c= a+b
a/c

0.7982496545370796

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7982496545370796

# decision Tree

In [58]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()

In [59]:
DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [62]:
y_pred = DT.predict(X_test)

In [64]:
DT.score(X_test,y_test)

0.8077690772301551

In [65]:
confusion_matrix(y_test,y_pred)

array([[4331,  627],
       [ 625,  930]], dtype=int64)

In [66]:
accuracy_score(y_test,y_pred)

0.8077690772301551

# Random Forest Regression

In [88]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [89]:
RF.fit(X_train,y_train)

RandomForestClassifier()

In [90]:
y_pred = RF.predict(X_test)

In [91]:
print(y_test.dtype, y_pred.dtype)  # Ensure both are integers


int32 int32


In [92]:
RF.score(X_test,y_test)

0.8435436818670352

In [93]:
confusion_matrix(y_test,y_pred)

array([[4581,  377],
       [ 642,  913]], dtype=int64)

In [94]:
accuracy_score(y_test,y_pred)

0.8435436818670352

In [115]:
RFC = RandomForestClassifier(n_estimators=200,max_depth=2,max_features=3,min_samples_leaf=1,random_state=57)

In [116]:
RFC.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, max_features=3, n_estimators=200,
                       random_state=57)

In [117]:
y_pred = RFC.predict(X_test)

In [118]:
RFC.score(X_test,y_test)

0.799324428066943

In [119]:
confusion_matrix(y_test,y_pred)

array([[4952,    6],
       [1301,  254]], dtype=int64)

In [120]:
accuracy_score(y_test,y_pred)

0.799324428066943

In [134]:
param_dist = {
    'n_estimators' : [100,200,300,400,500],
    'max_depth' : [None,10,20,30,40],
    'min_samples_split' : [2,5,10],
    'min_samples_leaf' : [1,2,4 ],
    'criterion' : ['gini','entropy'],
    'max_features' : ['sqrt','log2']
}

# Random Search CV

In [135]:
from sklearn.model_selection import RandomizedSearchCV

rf_classifier = RandomizedSearchCV(RandomForestClassifier(),param_distributions=param_dist,n_iter=10)

In [136]:
rf_classifier.fit(X_train,y_train)

RandomizedSearchCV(estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [None, 10, 20, 30, 40],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500]})

In [137]:
y_pred = rf_classifier.predict(X_test)

In [138]:
rf_classifier.score(X_test,y_test)

0.8545984953170582

In [139]:
confusion_matrix(y_test,y_pred)

array([[4658,  300],
       [ 647,  908]], dtype=int64)

In [140]:
accuracy_score(y_test,y_pred)

0.8545984953170582